[38;5;245m12:34:56.78 [0m[36m[1m>>> Call to main in File "/path/to_file.py", line 15[0m
[38;5;245m12:34:56.78 [0m[38;5;245m  15[0m | [38;5;81mdef[39m [38;5;148mmain[39m():
[38;5;245m12:34:56.78 [0m[38;5;245m  16[0m |     [38;5;81mtry[39m:
[38;5;245m12:34:56.78 [0m[38;5;245m  17[0m |         ([38;5;81mNone[39m
[38;5;245m12:34:56.78 [0m[38;5;245m  18[0m |          [38;5;204mor[39m foo)()
[38;5;245m12:34:56.78 [0m[38;5;245m  17[0m |         ([38;5;81mNone[39m
[38;5;245m    12:34:56.78 [0m[36m[1m>>> Call to foo in File "/path/to_file.py", line 10[0m
[38;5;245m    12:34:56.78 [0m[38;5;245m  10[0m | [38;5;81mdef[39m [38;5;148mfoo[39m():
[38;5;245m    12:34:56.78 [0m[38;5;245m  11[0m |     [38;5;81mraise[39m [38;5;148mTypeError[39m
[38;5;245m    12:34:56.78 [0m[31m[1m!!! TypeError[0m
[38;5;245m    12:34:56.78 [0m[31m[1m!!! Call ended by exception[0m
[38;5;245m12:34:56.78 [0m[38;5;245m  17[0m |         ([38;5;81mNone[39m
[38;5;245m12:34:56.78 [0m[31m[1m!!! TypeError[0m
[38;5;245m12:34:56.78 [0m[31m[1m!!! When calling: [0m(None
[38;5;245m12:34:56.78 [0m                   or foo)()
[38;5;245m12:34:56.78 [0m[38;5;245m  19[0m |     [38;5;81mexcept[39m:
[38;5;245m12:34:56.78 [0m[38;5;245m  20[0m |         [38;5;81mpass[39m
[38;5;245m12:34:56.78 [0m[38;5;245m  21[0m |     x [38;5;204m=[39m [38;5;141m1[39m
[38;5;245m12:34:56.78 [0m[38;5;245m  22[0m |     y [38;5;204m=[39m [38;5;141m2[39m
[38;5;245m12:34:56.78 [0m[38;5;245m  23[0m |     pp(
[38;5;245m12:34:56.78 [0m[38;5;245m  25[0m |             x [38;5;204m+[39m y
[38;5;245m12:34:56.78 [0m[38;5;245m  24[0m |         [
[38;5;245m12:34:56.78 [0m[38;5;245m  23[0m |     pp(
[38;5;245m12:34:56.78 [0mLOG:
[38;5;245m12:34:56.78 [0m.... [
[38;5;245m12:34:56.78 [0m         x [38;5;204m+[39m y
[38;5;245m12:34:56.78 [0m     ] = [[38;5;141m3[39m]
[38;5;245m12:34:56.78 [0m[32m[1m<<< Return value from main: [0m[38;5;81mNone[39m